<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\SRDCombat.Content\SRDCombat.Content.csproj" />
    <ProjectReference Include="..\..\src\SRDCombat.Game\SRDCombat.Game.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
