namespace SRDCombat.Viewer.Tests;

/// <summary>One shipped sheet's pinned geometry — see <see cref="SpriteGeometryTests"/>.</summary>
internal readonly record struct SpriteGeometryEntry(string RelativePath, int Width, int Height, int FrameCount);

/// <summary>
/// Reads and writes the committed manifest of every shipped sheet's canvas dimensions
/// (#467). Same shape and same discipline as the frozen transcript
/// (<c>FrozenTranscriptTests</c>/<c>TranscriptWriter</c>): a plain text fixture, one
/// line per sheet, regenerated only deliberately and reviewed as a diff — a manifest
/// that silently rewrote itself on every run would gate nothing.
/// </summary>
internal static class SpriteGeometryManifest
{
    public const string FixtureName = "sprite-geometry-manifest.tsv";

    private const char Separator = '\t';

    /// <summary>
    /// Every <c>.png</c> actually under <c>client/assets/sprites</c> right now, measured
    /// from its header bytes (<see cref="PngGeometry"/>) — the tree's present truth,
    /// not the committed one. <see cref="SpriteGeometryTests"/> is what compares the two.
    /// </summary>
    public static List<SpriteGeometryEntry> MeasureShippedTree()
    {
        var root = ViewerRepositoryPaths.SpritesDirectory;

        return Directory.EnumerateFiles(root, "*.png", SearchOption.AllDirectories)
            .Select(path =>
            {
                var (width, height) = PngGeometry.Read(path);
                var relativePath = Path.GetRelativePath(root, path).Replace('\\', '/');
                return new SpriteGeometryEntry(relativePath, width, height, FrameCountFor(width, height));
            })
            .OrderBy(entry => entry.RelativePath, StringComparer.Ordinal)
            .ToList();
    }

    /// <summary>
    /// <c>SpriteLibrary.LoadStrip</c>'s own rule, applied to the file as shipped rather
    /// than as loaded: a sheet narrower than it is tall is one drawing, padded to a
    /// single square frame at load time rather than rejected, so it always measures as
    /// one frame; anything else is however many <c>height</c>-wide frames its width
    /// holds.
    /// </summary>
    private static int FrameCountFor(int width, int height) => height <= 0 ? 0 : Math.Max(width, height) / height;

    public static List<SpriteGeometryEntry> Load(string path)
    {
        if (!File.Exists(path))
        {
            return [];
        }

        var entries = new List<SpriteGeometryEntry>();

        foreach (var line in File.ReadAllLines(path))
        {
            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            var fields = line.Split(Separator);

            if (fields.Length != 4)
            {
                throw new InvalidDataException(
                    $"Malformed line in the sprite geometry manifest (expected 4 tab-separated fields, got {fields.Length}): '{line}'");
            }

            entries.Add(new SpriteGeometryEntry(fields[0], int.Parse(fields[1]), int.Parse(fields[2]), int.Parse(fields[3])));
        }

        return entries;
    }

    public static void Write(string path, IReadOnlyList<SpriteGeometryEntry> entries)
    {
        var lines = new List<string>
        {
            "# Generated by SpriteGeometryManifestWriter (#467) — do not hand-edit.",
            "# RelativePath\tWidth\tHeight\tFrameCount",
        };

        lines.AddRange(entries
            .OrderBy(entry => entry.RelativePath, StringComparer.Ordinal)
            .Select(entry => $"{entry.RelativePath}{Separator}{entry.Width}{Separator}{entry.Height}{Separator}{entry.FrameCount}"));

        File.WriteAllLines(path, lines);
    }
}
