#!/usr/bin/env bash
#
# Generates docs/status.md — the measured half of what CLAUDE.md's "Current state"
# table used to carry by hand.
#
# The split this script rests on: **it generates facts, never readings.** Content
# counts, line counts, test counts and git position are mechanical, and every hand-
# maintained copy of them drifted (the table read 4,718 tests against a measured
# 4,814 on the day this was written). What a script cannot produce is the paragraph
# next to the number — that the pacing median saturates at 18 so `shape:` is the
# line to read, or that "N% untested" was retired because a directory proxy stopped
# being reproducible. Those are judgements, they live in CLAUDE.md, and this script
# deliberately does not try to write them.
#
#   ./scripts/status.sh            # cheap: content, lines, git. Tests from a trx if one exists.
#   ./scripts/status.sh --tests    # runs the suite first so the test counts are current
#
set -euo pipefail
repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"
OUT=docs/status.md

if [[ "${1:-}" == "--tests" ]]; then
  echo "Running the suite to refresh test counts..." >&2
  rm -rf TestResults
  # No LogFileName: `dotnet test` on a solution runs five test projects, and forcing one
  # filename makes them overwrite each other — which silently reported 388 tests instead
  # of 4,814 the first time this ran. Let each project write its own trx; aggregate below.
  dotnet test SRDCombat.sln -c Debug --logger trx \
    --results-directory ./TestResults --logger "console;verbosity=minimal" >&2
fi

lines() { find "$@" -name '*.cs' -not -path '*/obj/*' -not -path '*/bin/*' -exec cat {} + 2>/dev/null | wc -l; }
items() { jq '.items|length' "data/srd/$1.json"; }

# Test counts come from trx (<Counters passed= failed= total=/> per assembly).
tests_block() {
  local trx_count; trx_count="$(find TestResults -name '*.trx' 2>/dev/null | wc -l)"
  if [[ "$trx_count" -eq 0 ]]; then
    echo "_No trx found. Re-run with \`./scripts/status.sh --tests\` to measure._"
    return
  fi
  find TestResults -name '*.trx' -print0 | xargs -0 python3 -c '
import sys, xml.etree.ElementTree as ET
NS={"t":"http://microsoft.com/schemas/VisualStudio/TeamTest/2010"}
rows=[]; T=P=F=S=0
for path in sys.argv[1:]:
    root=ET.parse(path).getroot()
    c=root.find(".//t:ResultSummary/t:Counters", NS)
    if c is None: continue
    tot,ok,bad=int(c.get("total")),int(c.get("passed")),int(c.get("failed"))
    skip=tot-ok-bad
    u=root.find(".//t:UnitTest", NS)
    name="(unknown)"
    if u is not None:
        st=u.get("storage") or ""
        name=st.replace("\\\\","/").split("/")[-1].removesuffix(".dll")
        # trx lowercases the storage path; recover the real casing from tests/.
        import os
        for d in sorted(os.listdir("tests")):
            if d.lower()==name.lower(): name=d; break
    rows.append((name,ok,bad,skip)); T+=tot; P+=ok; F+=bad; S+=skip
print(f"**{P:,} passing**, {F} failed, {S} skipped, {T:,} total, across {len(rows)} test projects.")
print()
print("| Test project | Passing | Skipped |")
print("| --- | ---: | ---: |")
for n,ok,bad,sk in sorted(rows, key=lambda r:-r[1]):
    print(f"| `{n}` | {ok:,} | {sk} |")
'
}

{
cat <<HDR
# Status — generated

<!-- GENERATED by scripts/status.sh. Do not hand-edit: your changes are overwritten.
     This file holds measurements only. The *readings* of those measurements — what a
     saturating pacing median means, why a coverage percentage was retired — stay in
     CLAUDE.md, which a script has no business writing. -->

Generated from \`$(git rev-parse --short HEAD)\` on branch \`$(git rev-parse --abbrev-ref HEAD)\`
($(git log -1 --format=%cs)). Regenerate with \`./scripts/status.sh --tests\`.

## Tests

$(tests_block)

## Content

Counted with \`jq '.items|length'\` over \`data/srd/\`. These are the book's totals, so
they are exact counts and not floors — see CLAUDE.md's extraction lesson on why a floor
is the wrong shape for a count the source fixes.

| Set | Count |
| --- | ---: |
| Monsters | $(items monsters) |
| Spells | $(items spells) |
| Classes | $(items classes) |
| Species | $(items species) |
| Backgrounds | $(items backgrounds) |
| Weapons | $(items weapons) |
| Armor | $(items armor) |
| Magic items | $(items magic-items) |

## Size

C# lines, excluding \`bin/\` and \`obj/\`.

| Tree | Lines |
| --- | ---: |
| \`src/\` | $(lines src) |
| &nbsp;&nbsp;of which \`src/SRDCombat.Console\` | $(lines src/SRDCombat.Console) |
| \`client/\` | $(lines client) |
| \`tools/\` | $(lines tools) |
| **Production total** | **$(( $(lines src) + $(lines client) + $(lines tools) ))** |
| \`tests/\` | $(lines tests) |

## What this file deliberately does not say

No coverage percentage. The old "24% untested" was a directory proxy that counted a
whole tree as untested the moment it lacked a test project, and it stopped being
reproducible once \`tools/SrdExtract\` and the Godot client got theirs. \`client/\` is
now neither untested nor tested but partly each, and one number cannot say which.
The specific, still-true gaps are tracked as issues — #317 (console client) and #490
(the live Godot argv boundary).

No pacing figures. Pacing is measured at re-baselining checkpoints, not per PR, and
its numbers need the reading that comes with them. The current baseline and its
interpretation live in CLAUDE.md.
HDR
} > "$OUT"

echo "wrote $OUT"
