<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\SRDCombat.Content\SRDCombat.Content.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PdfPig" Version="0.1.16" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SrdExtract.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
